import Header from "@/components/Header";
import AppProviders from "@/app/AppProviders";
import "@scss/_global.scss";
import { Roboto } from "next/font/google";

export const metadata = {
  title: "BKrental",
  description: "Generated by Next.js",
};

const roboto = Roboto({
  subsets: ["latin", "vietnamese"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
      </head>
      <body suppressHydrationWarning={true} className={roboto.className}>
        <AppProviders>
          <div style={{ paddingTop: "env(safe-area-inset-top)" }}>
            <Header />
            {children}
          </div>
        </AppProviders>
      </body>
    </html>
  );
}
